spring:
  security:
    user:
      name: user
      password: 123456
  datasource:
    generate-unique-name: false
    name: tacocloud
  data:
    rest:
      base-path: /data-api

taco:
  orders:
    pageSize: 10

---
spring:
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword
  config:
    activate:
      on-profile: prod

logging:
  level:
    tacos: WARN